### ISSUE TITLE
ג

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/Starbucks-Menu-Analyzation#4]
- [x] בחרו שני משתנים מספריים מקובץ הנתונים
- [x] חשבו את המתאם ביניהם והכניסו אותו למשתנה בשם cor_value1. 
- [x] כעת, כתבו לולאה שתחשב את המתאם 250 פעמים על 70% מהתצפיות במשתנה, שיידגמו מקרית בכל פעם. 
    - [x] הכניסו את התוצאות לווקטור בשם cor_vector2. השתמשו בחבילת ggplot2 להצגת התפלגות התוצאות בווקטור cor_vector2, וסמנו על תרשים ההתפלגות את הערך cor_value1.

**Comment by ISHIBubble** [comment]
- [x] לבדוק באיזה מתאם מדובר
- [x] להבין אם להעיף את הsort
