### ISSUE TITLE
ה

### ISSUE THREAD

**Issue by rosenpin** [rosenpin/Starbucks-Menu-Analyzation#6]
- [x] בחרו שני משתנים קטגוריאליים (=בסולם שמי) מהקובץ. 
- [x] חשבו את ההסתברות המותנית עבור כל אחת מהקטגוריות של המשתנה הראשון בכל אחת מהקטגוריות של המשתנה השני. 
- [x] כיתבו את ההסתברויות המותנות ואת הסתברויות החיתוכים. 
- [x] האם יש תלות בין המשתנים?

**Comment by rosenpin** [comment]
- [x] לכתוב תיעוד
- [x] לסיים שאלה

**Comment by ISHIBubble** [comment]
- [x] להעיף את הפונקציית עזר!
